---
- name: Deploy Nginx and PHP
  hosts: webServer
  user: root
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  # gather_facts: false

  roles:
  - role: common
  - role: php
  - role: nginx
  - role: mysql